_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 71
                - 105
            "2":
                - 1
                - 41
                - 49
                - 71
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cpu
epochs:
    value: 5
lr:
    value: 0.001
model:
    value: SimpleCNN
